### PR TITLE
gotta go even faster

### PR DESCRIPTION
**Pull request by SimonSchick**
local test is about 5% faster.

### CODE REVIEW

**Comment by SimonSchick** [comment]
Also fixed global variable leak 😛

**Comment by connor4312** [comment]
I tried running both branches on my machine, running them twice to eliminate any weird warmups. Results:

```
                      head-to-head
          19,591 op/s » master
          20,193 op/s » speed-improvements
          20,148 op/s » master
          19,613 op/s » speed-improvements


  Suites:  1
  Benches: 4
  Elapsed: 53,147.79 ms
```

**Comment by SimonSchick** [comment]
This is odd, on my machine I got an average of 5%.

What node version were you running?

**Comment by connor4312** [comment]
These were the results on the raccoons VM, much less noisy (+/- under 40 ops/sec):

```
                      head-to-head
          20,906 op/s » master
          20,540 op/s » speed-improvements
          20,939 op/s » master
          20,517 op/s » speed-improvements


  Suites:  1
  Benches: 4
  Elapsed: 53,380.37 ms
```

Both Node 4.x

**Comment by SimonSchick** [comment]
That explains that, I ran it against v6 since that uses the newest v8 engine, if you want you can close this, but please fix the global variable leak (and possible add strict mode to prevent them in the future).

**Comment by SimonSchick** [comment]
Feel free to close this PR, but you might want to run it against v6 and inside a browser as well.

Also make sure to fix that global leak.

**Comment by connor4312** [comment]
sure thing

**Pull request closed without merging**
